In [1]:
from diffusion import forward_diffusion_sample
import torch

In [2]:
num_diffusion_steps = 1000
betas = torch.linspace(0.0001, 0.02, num_diffusion_steps)

batch_size =  4
dim = 10

x_0 = torch.randn(batch_size, dim)

In [3]:
betas.shape

torch.Size([1000])

In [4]:
x_0.shape

torch.Size([4, 10])

In [5]:
timestep = 50
timestep_tensor = torch.full((batch_size,), timestep, dtype=torch.long) # Tensor shaped (batch_size,) with timestep repeated batch_size times

In [6]:
x_t,noise = forward_diffusion_sample(x_0, timestep_tensor,betas)

In [7]:

print("Clean sample (x_0):")
print(x_0)
print("\nNoisy sample (x_t):")
print(x_t)
print("\nNoise added:")
print(noise)

Clean sample (x_0):
tensor([[ 0.1289,  1.2353,  0.4951, -0.5941,  0.9091, -2.4496, -1.1601,  0.7472,
          0.9987, -0.0277],
        [ 1.1224,  0.0131,  0.2411, -0.4904, -1.4988,  0.1941,  0.9542,  0.6246,
         -0.3093,  1.1427],
        [-0.1251, -1.9981,  0.0297,  0.4134,  0.6649,  0.3738,  1.0905,  2.1470,
          0.1550,  1.2265],
        [ 0.1750, -0.4440,  1.8210, -0.5959,  0.6082, -0.7949,  0.6316,  1.2487,
         -1.1915,  0.6133]])

Noisy sample (x_t):
tensor([[ 0.0329,  1.3515,  0.2929, -0.3607,  0.6868, -2.7179, -1.2975,  0.7080,
          0.9692,  0.1483],
        [ 0.9277,  0.1480,  0.0658, -0.4784, -1.4647,  0.0577,  0.9844,  0.4709,
         -0.4477,  1.2396],
        [-0.2062, -1.9331, -0.1775,  0.6897,  0.3664,  0.3046,  1.0970,  2.0510,
          0.0666,  1.2832],
        [ 0.1346, -0.5330,  1.7441, -0.6661,  0.2818, -0.7349,  0.8008,  1.2485,
         -0.9270,  0.6817]])

Noise added:
tensor([[-0.5424,  0.7780, -1.1230,  1.2949, -1.2032, -1.7616, -0.8936,