In [15]:
from diffusion import forward_diffusion_sample
import torch
from diffusion import get_time_embedding
from diffusion import model_architecture
from diffusion import reverse_diffusion_sample

# Forward diffusion test

In [16]:
num_diffusion_steps = 1000
betas = torch.linspace(0.0001, 0.02, num_diffusion_steps)

batch_size =  4
dim = 10

x_0 = torch.randn(batch_size, dim)

In [17]:
betas.shape

torch.Size([1000])

In [18]:
x_0.shape

torch.Size([4, 10])

In [19]:
timestep = 50
timestep_tensor = torch.full((batch_size,), timestep, dtype=torch.long) # Tensor shaped (batch_size,) with timestep repeated batch_size times

In [20]:
timestep_tensor.shape

torch.Size([4])

In [21]:
x_t,noise = forward_diffusion_sample(x_0, timestep_tensor,betas)

In [22]:

print("Clean sample (x_0):")
print(x_0)
print("\nNoisy sample (x_t):")
print(x_t)
print("\nNoise added:")
print(noise)

Clean sample (x_0):
tensor([[ 1.4750, -0.3938, -0.4552, -1.6739,  0.8467,  1.0316,  0.9094, -0.4057,
         -0.9085, -0.4406],
        [ 0.8871,  1.2570, -0.2101, -1.3765,  0.6372,  0.5948, -1.3427,  2.4970,
          1.5104,  1.5017],
        [ 0.2432,  1.4318, -0.5506,  0.4336,  0.2242, -0.9029,  0.6744,  1.0569,
          1.0807,  1.3416],
        [ 0.1433,  0.9565, -0.8070,  0.1681, -0.4470,  0.6217,  1.5089,  0.6798,
          0.2231, -0.0413]])

Noisy sample (x_t):
tensor([[ 1.2194, -0.4151, -0.7382, -1.3455,  0.5508,  0.7636,  1.1034, -0.2733,
         -1.0079, -0.5609],
        [ 0.6060,  1.1153, -0.0248, -1.4095,  0.5671,  0.7894, -1.1267,  2.5681,
          1.2953,  1.4257],
        [ 0.2092,  1.3063, -0.6171,  0.4502,  0.4828, -0.9745,  0.6418,  1.2699,
          0.7880,  1.5301],
        [ 0.3794,  1.2219, -0.6230,  0.1375, -0.7460,  0.7359,  1.1333,  0.6272,
          0.1124, -0.1248]])

Noise added:
tensor([[-1.3452, -0.1572, -1.6727,  1.7481, -1.6329, -1.4560,  1.1982,

# Time embedding test

In [23]:
test = get_time_embedding(timestep_tensor, 32)

In [24]:
print(test)
print(test.shape)

tensor([[-0.2624,  0.1566, -0.1032,  0.5084, -0.9589,  0.3239,  0.9999,  0.7765,
          0.4794,  0.2775,  0.1575,  0.0888,  0.0500,  0.0281,  0.0158,  0.0089,
          0.9650, -0.9877, -0.9947, -0.8611,  0.2837, -0.9461, -0.0103,  0.6301,
          0.8776,  0.9607,  0.9875,  0.9960,  0.9988,  0.9996,  0.9999,  1.0000],
        [-0.2624,  0.1566, -0.1032,  0.5084, -0.9589,  0.3239,  0.9999,  0.7765,
          0.4794,  0.2775,  0.1575,  0.0888,  0.0500,  0.0281,  0.0158,  0.0089,
          0.9650, -0.9877, -0.9947, -0.8611,  0.2837, -0.9461, -0.0103,  0.6301,
          0.8776,  0.9607,  0.9875,  0.9960,  0.9988,  0.9996,  0.9999,  1.0000],
        [-0.2624,  0.1566, -0.1032,  0.5084, -0.9589,  0.3239,  0.9999,  0.7765,
          0.4794,  0.2775,  0.1575,  0.0888,  0.0500,  0.0281,  0.0158,  0.0089,
          0.9650, -0.9877, -0.9947, -0.8611,  0.2837, -0.9461, -0.0103,  0.6301,
          0.8776,  0.9607,  0.9875,  0.9960,  0.9988,  0.9996,  0.9999,  1.0000],
        [-0.2624,  0.1566

# Reverse diffusion process

In [25]:
x_t_minus_1 = reverse_diffusion_sample(x_t, betas, timestep_tensor, model_architecture)

x_T shape: torch.Size([4, 10])
time_embedding shape: torch.Size([4, 2])
x shape: torch.Size([4, 12])


In [15]:
print(f" Original sample (x_t): {x_t}")
print(f" Noise added: {noise}")
print(f" Reversed sample (x_t-1): {x_t_minus_1}")

 Original sample (x_t): tensor([[ 0.9129,  0.9456,  1.9236,  0.6603,  0.0957, -0.8940,  1.2359,  1.8455,
          2.4707, -0.1314],
        [ 0.4904,  0.2617, -0.1398, -0.3541,  0.0190,  0.6403,  1.2285,  0.5831,
          0.2228,  0.3880],
        [-0.7446, -0.3469, -1.2333,  0.9391, -1.0112,  1.4118,  0.7305,  0.3503,
         -0.8563,  0.0370],
        [ 1.6883,  1.1925, -0.6067, -0.5078, -0.9327, -0.2396,  1.2374, -0.2426,
         -0.5686, -0.3173]])
 Noise added: tensor([[-0.5921,  0.8497,  1.6738,  0.4271, -1.4904, -0.8752, -1.5927, -0.7021,
          0.9303,  0.0672],
        [-0.7069,  0.5148, -0.2175,  0.2886,  0.1850,  0.9603, -0.7536, -0.7710,
          1.1935,  1.2176],
        [ 1.0512, -1.2152,  1.1807,  0.4453, -0.5517,  1.9664,  0.4839, -0.1953,
          0.0798, -0.0605],
        [ 0.0398,  0.3673,  0.4900, -0.7888, -0.4366,  0.5434, -1.3997,  0.6173,
         -1.0215, -1.7815]])
 Reversed sample (x_t-1): tensor([[ 0.9119,  0.9473,  1.9252,  0.6607,  0.0961, -0.8930,

# Training of model

In [1]:
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
import pandas as pd
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from diffusion import run_reverse_diffusion

In [2]:
import sys
import os

module_path = os.path.abspath(os.path.join('../Datasets'))
if module_path not in sys.path:
    sys.path.append(module_path)

from multi_target_dataset import StockDiffusionDataset

In [3]:
base_path = "../../price/raw"
df = pd.read_csv(f"{base_path}/AAPL.csv")
print(len(df))

1258


In [4]:
# 1. Daily Return (percentage change from open to close)
df['Return'] = (df['Close'] - df['Open']) / df['Open']

# 2. Price Difference (Close - Open)
df['Diff'] = df['Close'] - df['Open']

# 3. High-Low Difference (as a measure of volatility)
df['HL_Diff'] = df['High'] - df['Low']

# 4. 5-day Moving Average of the Close (shifted to avoid leakage)
df['MA5'] = df['Close'].rolling(window=5).mean().shift(1)

# 5. 5-day Moving Average of the Return (shifted)
df['Return_MA5'] = df['Return'].rolling(window=5).mean().shift(1)

# Drop rows with NaN values that result from rolling and shifting
df.dropna(inplace=True)
df.reset_index(drop=True, inplace=True)

In [5]:
df.head()

Date       Open       High        Low      Close  Adj Close  \
0  2012-09-11  95.015717  95.728569  93.785713  94.370003  85.265068   
1  2012-09-12  95.264282  95.699997  93.714287  95.684288  86.452538   
2  2012-09-13  96.767143  97.928574  96.395714  97.568573  88.155037   
3  2012-09-14  98.565712  99.568573  98.269997  98.754288  89.226341   
4  2012-09-17  99.907143  99.971428  99.230003  99.968575  90.323479   

      Volume    Return      Diff   HL_Diff        MA5  Return_MA5  
0  125995800 -0.006796 -0.645714  1.942856  96.132857   -0.002394  
1  178058300  0.004409  0.420006  1.985710  95.722000   -0.006519  
2  149590000  0.008282  0.801430  1.532860  95.709428   -0.004057  
3  150118500  0.001913  0.188576  1.298576  95.901143   -0.003321  
4   99507800  0.000615  0.061432  0.741425  96.210858   -0.003644

In [6]:
feature_columns = ['Open', 'High', 'Low', 'Volume', 'Return', 'Diff', 'HL_Diff', 'MA5', 'Return_MA5']
# We keep the target as the raw 'Close' (normalized later)
target_column = 'Close'

filtered_df = df[feature_columns + [target_column]]

seq_len = 10

# Split into training and test data 
train_size = int(len(filtered_df) * 0.8)
train_data = filtered_df.iloc[:train_size].copy()
test_data = filtered_df.iloc[train_size:].copy()


In [7]:
train_data

Open        High         Low     Volume    Return      Diff  \
0      95.015717   95.728569   93.785713  125995800 -0.006796 -0.645714   
1      95.264282   95.699997   93.714287  178058300  0.004409  0.420006   
2      96.767143   97.928574   96.395714  149590000  0.008282  0.801430   
3      98.565712   99.568573   98.269997  150118500  0.001913  0.188576   
4      99.907143   99.971428   99.230003   99507800  0.000615  0.061432   
...          ...         ...         ...        ...       ...       ...   
997   106.620003  107.440002  106.290001   24970300  0.001876  0.199997   
998   105.800003  106.500000  105.500000   24863900  0.001890  0.199997   
999   105.660004  106.570000  105.639999   29662400  0.004164  0.439994   
1000  106.139999  106.800003  105.620003   26701500  0.005559  0.590004   
1001  107.699997  108.000000  106.820000   26802500  0.000279  0.030006   

       HL_Diff         MA5  Return_MA5       Close  
0     1.942856   96.132857   -0.002394   94.370003  
1     1.985710   95.722000   -0.006519   95.684288  
2     1.532860   95.709428   -0.004057   97.568573  
3     1.298576   95.901143   -0.003321   98.754288  
4     0.741425   96.210858   -0.003644   99.968575  
...        ...         ...         ...         ...  
997   1.150001  107.980000   -0.001699  106.820000  
998   1.000000  107.642000   -0.000681  106.000000  
999   0.930001  107.072000   -0.000781  106.099998  
1000  1.180000  106.686000    0.001046  106.730003  
1001  1.180000  106.518001    0.001823  107.730003  

[1002 rows x 10 columns]

In [8]:
scaler = MinMaxScaler()
scaler.fit(train_data)

# Transform train and test sets.
train_data.loc[:, train_data.columns] = scaler.transform(train_data)
test_data.loc[:, test_data.columns] = scaler.transform(test_data)
print("Done")


Done


/tmp/ipykernel_1486132/3772158868.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.32072709 0.46856191 0.38772434 ... 0.0471822  0.03877453 0.03906133]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  train_data.loc[:, train_data.columns] = scaler.transform(train_data)
/tmp/ipykernel_1486132/3772158868.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.03928253  0.08325006  0.1134565   0.0951555   0.09156573  0.13950723
  0.27782951  0.21846813  0.1897979   0.09647874  0.06095948  0.06518731
  0.05119053  0.11197765  0.04776999  0.0328282   0.04712172  0.06485735
  0.0662547   0.02457757  0.04739346  0.02387137  0.04467458  0.03212115
  0.06584836  0.14480245  0.06968404  0.06288499  0.06419062  0.03003833
  0.03267515  0.01984344  0.03146067  0.02881107  0.02979356  0.0996193
  0.15074622  0.

# No context window

In [9]:
target_column= ['Open', 'High', 'Low', 'Volume', 'Return', 'Diff', 'HL_Diff', 'MA5', 'Return_MA5']

train_dataset = StockDiffusionDataset(train_data, target_column=target_column)
test_dataset = StockDiffusionDataset(test_data, target_column=target_column)
print("Datasets created successfully!")

Datasets created successfully!


In [10]:
#Visualize the first sample
sample = train_dataset[1]
print(sample)


tensor([0.5041, 0.4985, 0.5066, 0.4686, 0.4615, 0.4987, 0.0934, 0.5208, 0.4064])


In [11]:
test_dataset[0]

tensor([0.6639, 0.6612, 0.6872, 0.0393, 0.4206, 0.4590, 0.0202, 0.6676, 0.6465])

In [12]:
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True, drop_last=True)
test_loader = DataLoader(test_dataset, batch_size=16, shuffle=False, drop_last=True)


In [13]:
for x0 in train_loader :
    # print(x0)
    print(x0.shape)
    break

torch.Size([16, 9])


In [14]:
from diffusion import model_architecture
from diffusion import forward_diffusion_sample
from diffusion import reverse_diffusion_sample

import torch.nn.functional as F
from diffusion import ResidualMLP
from diffusion import cosine_beta_schedule
from diffusion import get_time_embedding

In [16]:
# Hyperparameters
num_diffusion_steps = 100  # Total diffusion steps
num_epochs = 500
batch_size = 16
learning_rate = 1e-3

# Create a beta schedule: linearly spaced between 0.0001 and 0.01
# betas = torch.linspace(0.0001, 0.01, num_diffusion_steps)
betas = cosine_beta_schedule(num_diffusion_steps, s=0.008)


# Since our targets are scalars, dim = 1
dim = 9
embedding_dim = 32  # As used in get_time_embedding
# Instantiate the denoising network
denoise_net = ResidualMLP(dim, embedding_dim, hidden_size=256)
# Define the optimizer
optimizer = torch.optim.Adam(denoise_net.parameters(), lr=learning_rate)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=50, gamma=0.5)


for epoch in range(num_epochs):
    for x0 in train_loader:
        # Ensure x0 is shaped as [batch_size, dim]
        # If needed, reshape x0 (for instance, x0 = x0.unsqueeze(1) if x0 is 1D)
        
        # Sample a random diffusion timestep for each sample in the batch
        t = torch.randint(0, num_diffusion_steps, (batch_size,), dtype=torch.long)
        
        # Generate the noisy sample and the true noise using forward diffusion
        x_t, true_noise = forward_diffusion_sample(x0, t, betas)
        
        # Compute time embedding for the sampled timesteps
        time_embedding = get_time_embedding(t, embedding_dim)
        
        # Concatenate x_t with the time embedding to form the input to the denoising network
        x_combined = torch.cat([x_t, time_embedding], dim=-1)
        
        # Predict the noise using the denoising network directly
        predicted_noise = denoise_net(x_combined)
        
        # Compute the loss between predicted noise and true noise
        loss = F.mse_loss(predicted_noise, true_noise)
        
        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(denoise_net.parameters(), max_norm=1.0)
        optimizer.step()
    
    scheduler.step()
    current_lr = optimizer.param_groups[0]['lr']
    print(f"Epoch {epoch+1}, Loss: {loss.item()}, LR: {current_lr}")

Epoch 1, Loss: 0.11238446831703186, LR: 0.001
Epoch 2, Loss: 0.12538421154022217, LR: 0.001
Epoch 3, Loss: 0.30721041560173035, LR: 0.001
Epoch 4, Loss: 0.1888454407453537, LR: 0.001
Epoch 5, Loss: 0.1009746640920639, LR: 0.001
Epoch 6, Loss: 0.11035870015621185, LR: 0.001
Epoch 7, Loss: 0.11740206182003021, LR: 0.001
Epoch 8, Loss: 0.12176602333784103, LR: 0.001
Epoch 9, Loss: 0.2108498364686966, LR: 0.001
Epoch 10, Loss: 0.07580403238534927, LR: 0.001
Epoch 11, Loss: 0.06457558274269104, LR: 0.001
Epoch 12, Loss: 0.09104500710964203, LR: 0.001
Epoch 13, Loss: 0.0872952863574028, LR: 0.001
Epoch 14, Loss: 0.14164350926876068, LR: 0.001
Epoch 15, Loss: 0.1007164865732193, LR: 0.001
Epoch 16, Loss: 0.20767970383167267, LR: 0.001
Epoch 17, Loss: 0.10886040329933167, LR: 0.001
Epoch 18, Loss: 0.10690119862556458, LR: 0.001
Epoch 19, Loss: 0.27944275736808777, LR: 0.001
Epoch 20, Loss: 0.03895974159240723, LR: 0.001
Epoch 21, Loss: 0.07538910955190659, LR: 0.001
Epoch 22, Loss: 0.080547571

In [17]:

denoise_net.eval()

# Define hyperparameters 
num_diffusion_steps = 100  
batch_size = 16            
dim = 9               

# Run the reverse diffusion chain starting from noise
generated_samples = run_reverse_diffusion(denoise_net, betas, num_diffusion_steps, batch_size, dim,embedding_dim)

print("Generated samples (predicted clean x0):")
print(generated_samples)


timestep: 99
timestep: 98
timestep: 97
timestep: 96
timestep: 95
timestep: 94
timestep: 93
timestep: 92
timestep: 91
timestep: 90
timestep: 89
timestep: 88
timestep: 87
timestep: 86
timestep: 85
timestep: 84
timestep: 83
timestep: 82
timestep: 81
timestep: 80
timestep: 79
timestep: 78
timestep: 77
timestep: 76
timestep: 75
timestep: 74
timestep: 73
timestep: 72
timestep: 71
timestep: 70
timestep: 69
timestep: 68
timestep: 67
timestep: 66
timestep: 65
timestep: 64
timestep: 63
timestep: 62
timestep: 61
timestep: 60
timestep: 59
timestep: 58
timestep: 57
timestep: 56
timestep: 55
timestep: 54
timestep: 53
timestep: 52
timestep: 51
timestep: 50
timestep: 49
timestep: 48
timestep: 47
timestep: 46
timestep: 45
timestep: 44
timestep: 43
timestep: 42
timestep: 41
timestep: 40
timestep: 39
timestep: 38
timestep: 37
timestep: 36
timestep: 35
timestep: 34
timestep: 33
timestep: 32
timestep: 31
timestep: 30
timestep: 29
timestep: 28
timestep: 27
timestep: 26
timestep: 25
timestep: 24
timestep: 23

In [18]:
import torch
import torch.nn.functional as F

# Set the model to evaluation mode
denoise_net.eval()

# Lists to store losses, predictions, and ground truths
all_losses = []
all_predictions = []
all_ground_truths = []

# Loop over the test DataLoader
with torch.no_grad():
    for x0 in test_loader:
        # Ensure x0 is of shape [batch_size, dim]
        if x0.dim() == 9:
            x0 = x0.unsqueeze(1)
        batch_size = x0.shape[0]

        # Initialize x_T as pure Gaussian noise (same shape as x0)
        x_T = torch.randn(batch_size, dim)

        # Run the full reverse diffusion chain from t = num_diffusion_steps - 1 down to 0
        x_t = x_T
        for t_val in reversed(range(num_diffusion_steps)):
            # Create a timestep tensor for the current reverse step (shape: [batch_size])
            t_tensor = torch.full((batch_size,), t_val, dtype=torch.long)
            # Perform one reverse diffusion step
            x_t = reverse_diffusion_sample(x_t, betas, t_tensor, embedding_dim, denoise_net)
        
        # The final x_t is the predicted clean sample x0_pred
        x0_pred = x_t

        # Compute the MSE loss between the predicted clean sample and the ground truth x0
        loss = F.mse_loss(x0_pred, x0)
        all_losses.append(loss.item())

        # Collect predictions and ground truth for further analysis (if needed)
        all_predictions.append(x0_pred)
        all_ground_truths.append(x0)

# Compute the average test MSE over all batches
average_loss = sum(all_losses) / len(all_losses)
print("Average Test MSE:", average_loss)

# Inspect a few predictions vs. ground truth:
for i in range(min(3, len(all_predictions))):
    print(f"Batch {i+1} predictions:\n", all_predictions[i])
    print(f"Batch {i+1} ground truth:\n", all_ground_truths[i])


Average Test MSE: 0.13089542190233866
Batch 1 predictions:
 tensor([[0.4926, 0.4916, 0.5046, 0.1148, 0.4353, 0.4745, 0.0596, 0.5008, 0.5853],
        [0.4995, 0.4986, 0.5116, 0.1135, 0.4351, 0.4742, 0.0602, 0.5081, 0.5855],
        [0.4918, 0.4908, 0.5038, 0.1151, 0.4351, 0.4742, 0.0595, 0.5000, 0.5852],
        [0.4908, 0.4897, 0.5027, 0.1153, 0.4351, 0.4742, 0.0594, 0.4989, 0.5850],
        [0.4899, 0.4888, 0.5018, 0.1155, 0.4351, 0.4743, 0.0594, 0.4980, 0.5848],
        [0.4983, 0.4974, 0.5104, 0.1137, 0.4353, 0.4744, 0.0601, 0.5068, 0.5855],
        [0.4889, 0.4878, 0.5008, 0.1157, 0.4350, 0.4742, 0.0592, 0.4970, 0.5849],
        [0.4991, 0.4983, 0.5113, 0.1136, 0.4354, 0.4744, 0.0601, 0.5077, 0.5856],
        [0.4960, 0.4951, 0.5080, 0.1142, 0.4352, 0.4743, 0.0599, 0.5044, 0.5856],
        [0.4902, 0.4891, 0.5021, 0.1155, 0.4352, 0.4743, 0.0594, 0.4983, 0.5850],
        [0.4887, 0.4876, 0.5006, 0.1157, 0.4352, 0.4744, 0.0593, 0.4967, 0.5850],
        [0.4988, 0.4979, 0.5110, 0.113