In [15]:
from diffusion import forward_diffusion_sample
import torch
from diffusion import get_time_embedding
from diffusion import model_architecture
from diffusion import reverse_diffusion_sample

# Forward diffusion test

In [16]:
num_diffusion_steps = 1000
betas = torch.linspace(0.0001, 0.02, num_diffusion_steps)

batch_size =  4
dim = 10

x_0 = torch.randn(batch_size, dim)

In [17]:
betas.shape

torch.Size([1000])

In [18]:
x_0.shape

torch.Size([4, 10])

In [19]:
timestep = 50
timestep_tensor = torch.full((batch_size,), timestep, dtype=torch.long) # Tensor shaped (batch_size,) with timestep repeated batch_size times

In [20]:
timestep_tensor.shape

torch.Size([4])

In [21]:
x_t,noise = forward_diffusion_sample(x_0, timestep_tensor,betas)

In [22]:

print("Clean sample (x_0):")
print(x_0)
print("\nNoisy sample (x_t):")
print(x_t)
print("\nNoise added:")
print(noise)

Clean sample (x_0):
tensor([[ 1.4750, -0.3938, -0.4552, -1.6739,  0.8467,  1.0316,  0.9094, -0.4057,
         -0.9085, -0.4406],
        [ 0.8871,  1.2570, -0.2101, -1.3765,  0.6372,  0.5948, -1.3427,  2.4970,
          1.5104,  1.5017],
        [ 0.2432,  1.4318, -0.5506,  0.4336,  0.2242, -0.9029,  0.6744,  1.0569,
          1.0807,  1.3416],
        [ 0.1433,  0.9565, -0.8070,  0.1681, -0.4470,  0.6217,  1.5089,  0.6798,
          0.2231, -0.0413]])

Noisy sample (x_t):
tensor([[ 1.2194, -0.4151, -0.7382, -1.3455,  0.5508,  0.7636,  1.1034, -0.2733,
         -1.0079, -0.5609],
        [ 0.6060,  1.1153, -0.0248, -1.4095,  0.5671,  0.7894, -1.1267,  2.5681,
          1.2953,  1.4257],
        [ 0.2092,  1.3063, -0.6171,  0.4502,  0.4828, -0.9745,  0.6418,  1.2699,
          0.7880,  1.5301],
        [ 0.3794,  1.2219, -0.6230,  0.1375, -0.7460,  0.7359,  1.1333,  0.6272,
          0.1124, -0.1248]])

Noise added:
tensor([[-1.3452, -0.1572, -1.6727,  1.7481, -1.6329, -1.4560,  1.1982,

# Time embedding test

In [23]:
test = get_time_embedding(timestep_tensor, 32)

In [24]:
print(test)
print(test.shape)

tensor([[-0.2624,  0.1566, -0.1032,  0.5084, -0.9589,  0.3239,  0.9999,  0.7765,
          0.4794,  0.2775,  0.1575,  0.0888,  0.0500,  0.0281,  0.0158,  0.0089,
          0.9650, -0.9877, -0.9947, -0.8611,  0.2837, -0.9461, -0.0103,  0.6301,
          0.8776,  0.9607,  0.9875,  0.9960,  0.9988,  0.9996,  0.9999,  1.0000],
        [-0.2624,  0.1566, -0.1032,  0.5084, -0.9589,  0.3239,  0.9999,  0.7765,
          0.4794,  0.2775,  0.1575,  0.0888,  0.0500,  0.0281,  0.0158,  0.0089,
          0.9650, -0.9877, -0.9947, -0.8611,  0.2837, -0.9461, -0.0103,  0.6301,
          0.8776,  0.9607,  0.9875,  0.9960,  0.9988,  0.9996,  0.9999,  1.0000],
        [-0.2624,  0.1566, -0.1032,  0.5084, -0.9589,  0.3239,  0.9999,  0.7765,
          0.4794,  0.2775,  0.1575,  0.0888,  0.0500,  0.0281,  0.0158,  0.0089,
          0.9650, -0.9877, -0.9947, -0.8611,  0.2837, -0.9461, -0.0103,  0.6301,
          0.8776,  0.9607,  0.9875,  0.9960,  0.9988,  0.9996,  0.9999,  1.0000],
        [-0.2624,  0.1566

# Reverse diffusion process

In [25]:
x_t_minus_1 = reverse_diffusion_sample(x_t, betas, timestep_tensor, model_architecture)

x_T shape: torch.Size([4, 10])
time_embedding shape: torch.Size([4, 2])
x shape: torch.Size([4, 12])


In [15]:
print(f" Original sample (x_t): {x_t}")
print(f" Noise added: {noise}")
print(f" Reversed sample (x_t-1): {x_t_minus_1}")

 Original sample (x_t): tensor([[ 0.9129,  0.9456,  1.9236,  0.6603,  0.0957, -0.8940,  1.2359,  1.8455,
          2.4707, -0.1314],
        [ 0.4904,  0.2617, -0.1398, -0.3541,  0.0190,  0.6403,  1.2285,  0.5831,
          0.2228,  0.3880],
        [-0.7446, -0.3469, -1.2333,  0.9391, -1.0112,  1.4118,  0.7305,  0.3503,
         -0.8563,  0.0370],
        [ 1.6883,  1.1925, -0.6067, -0.5078, -0.9327, -0.2396,  1.2374, -0.2426,
         -0.5686, -0.3173]])
 Noise added: tensor([[-0.5921,  0.8497,  1.6738,  0.4271, -1.4904, -0.8752, -1.5927, -0.7021,
          0.9303,  0.0672],
        [-0.7069,  0.5148, -0.2175,  0.2886,  0.1850,  0.9603, -0.7536, -0.7710,
          1.1935,  1.2176],
        [ 1.0512, -1.2152,  1.1807,  0.4453, -0.5517,  1.9664,  0.4839, -0.1953,
          0.0798, -0.0605],
        [ 0.0398,  0.3673,  0.4900, -0.7888, -0.4366,  0.5434, -1.3997,  0.6173,
         -1.0215, -1.7815]])
 Reversed sample (x_t-1): tensor([[ 0.9119,  0.9473,  1.9252,  0.6607,  0.0961, -0.8930,

# Training of model

In [1]:
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
import pandas as pd
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
from sklearn.preprocessing import MinMaxScaler

In [2]:
import sys
import os

module_path = os.path.abspath(os.path.join('../Datasets'))
if module_path not in sys.path:
    sys.path.append(module_path)

from custom_dataset import StockDiffusionDataset

In [3]:
base_path = "../price/raw"
df = pd.read_csv(f"{base_path}/AAPL.csv")
print(len(df))

1258


In [4]:
# 1. Daily Return (percentage change from open to close)
df['Return'] = (df['Close'] - df['Open']) / df['Open']

# 2. Price Difference (Close - Open)
df['Diff'] = df['Close'] - df['Open']

# 3. High-Low Difference (as a measure of volatility)
df['HL_Diff'] = df['High'] - df['Low']

# 4. 5-day Moving Average of the Close (shifted to avoid leakage)
df['MA5'] = df['Close'].rolling(window=5).mean().shift(1)

# 5. 5-day Moving Average of the Return (shifted)
df['Return_MA5'] = df['Return'].rolling(window=5).mean().shift(1)

# Drop rows with NaN values that result from rolling and shifting
df.dropna(inplace=True)
df.reset_index(drop=True, inplace=True)

In [5]:
df.head()

Date       Open       High        Low      Close  Adj Close  \
0  2012-09-11  95.015717  95.728569  93.785713  94.370003  85.265068   
1  2012-09-12  95.264282  95.699997  93.714287  95.684288  86.452538   
2  2012-09-13  96.767143  97.928574  96.395714  97.568573  88.155037   
3  2012-09-14  98.565712  99.568573  98.269997  98.754288  89.226341   
4  2012-09-17  99.907143  99.971428  99.230003  99.968575  90.323479   

      Volume    Return      Diff   HL_Diff        MA5  Return_MA5  
0  125995800 -0.006796 -0.645714  1.942856  96.132857   -0.002394  
1  178058300  0.004409  0.420006  1.985710  95.722000   -0.006519  
2  149590000  0.008282  0.801430  1.532860  95.709428   -0.004057  
3  150118500  0.001913  0.188576  1.298576  95.901143   -0.003321  
4   99507800  0.000615  0.061432  0.741425  96.210858   -0.003644

In [6]:
feature_columns = ['Open', 'High', 'Low', 'Volume', 'Return', 'Diff', 'HL_Diff', 'MA5', 'Return_MA5']
# We keep the target as the raw 'Close' (normalized later)
target_column = 'Close'

filtered_df = df[feature_columns + [target_column]]

seq_len = 10

# Split into training and test data 
train_size = int(len(filtered_df) * 0.8)
train_data = filtered_df.iloc[:train_size].copy()
test_data = filtered_df.iloc[train_size:].copy()


In [7]:
train_data

Open        High         Low     Volume    Return      Diff  \
0      95.015717   95.728569   93.785713  125995800 -0.006796 -0.645714   
1      95.264282   95.699997   93.714287  178058300  0.004409  0.420006   
2      96.767143   97.928574   96.395714  149590000  0.008282  0.801430   
3      98.565712   99.568573   98.269997  150118500  0.001913  0.188576   
4      99.907143   99.971428   99.230003   99507800  0.000615  0.061432   
...          ...         ...         ...        ...       ...       ...   
997   106.620003  107.440002  106.290001   24970300  0.001876  0.199997   
998   105.800003  106.500000  105.500000   24863900  0.001890  0.199997   
999   105.660004  106.570000  105.639999   29662400  0.004164  0.439994   
1000  106.139999  106.800003  105.620003   26701500  0.005559  0.590004   
1001  107.699997  108.000000  106.820000   26802500  0.000279  0.030006   

       HL_Diff         MA5  Return_MA5       Close  
0     1.942856   96.132857   -0.002394   94.370003  
1     1.985710   95.722000   -0.006519   95.684288  
2     1.532860   95.709428   -0.004057   97.568573  
3     1.298576   95.901143   -0.003321   98.754288  
4     0.741425   96.210858   -0.003644   99.968575  
...        ...         ...         ...         ...  
997   1.150001  107.980000   -0.001699  106.820000  
998   1.000000  107.642000   -0.000681  106.000000  
999   0.930001  107.072000   -0.000781  106.099998  
1000  1.180000  106.686000    0.001046  106.730003  
1001  1.180000  106.518001    0.001823  107.730003  

[1002 rows x 10 columns]

In [8]:
scaler = MinMaxScaler()
scaler.fit(train_data)

# Transform train and test sets.
train_data.loc[:, train_data.columns] = scaler.transform(train_data)
test_data.loc[:, test_data.columns] = scaler.transform(test_data)
print("Done")


Done


/tmp/ipykernel_57825/3772158868.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.32072709 0.46856191 0.38772434 ... 0.0471822  0.03877453 0.03906133]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  train_data.loc[:, train_data.columns] = scaler.transform(train_data)
/tmp/ipykernel_57825/3772158868.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.03928253  0.08325006  0.1134565   0.0951555   0.09156573  0.13950723
  0.27782951  0.21846813  0.1897979   0.09647874  0.06095948  0.06518731
  0.05119053  0.11197765  0.04776999  0.0328282   0.04712172  0.06485735
  0.0662547   0.02457757  0.04739346  0.02387137  0.04467458  0.03212115
  0.06584836  0.14480245  0.06968404  0.06288499  0.06419062  0.03003833
  0.03267515  0.01984344  0.03146067  0.02881107  0.02979356  0.0996193
  0.15074622  0.0610

# No context window

In [9]:
train_dataset = StockDiffusionDataset(train_data, target_column=target_column)
test_dataset = StockDiffusionDataset(test_data, target_column=target_column)
print("Datasets created successfully!")

Datasets created successfully!


In [10]:
#Visualize the first sample
sample = train_dataset[0]
print(sample)


tensor([0.4997])


In [11]:
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True, drop_last=True)
test_loader = DataLoader(test_dataset, batch_size=16, shuffle=False, drop_last=True)


In [12]:
for x0 in train_loader :
    # print(x0)
    print(x0.shape)
    break

torch.Size([16, 1])


In [13]:
from diffusion import model_architecture
from diffusion import forward_diffusion_sample
from diffusion import reverse_diffusion_sample

import torch.nn.functional as F

In [14]:
# Hyperparameters
num_diffusion_steps = 100  # Total diffusion steps
num_epochs = 30
batch_size = 16
learning_rate = 1e-3

# Create a beta schedule: linearly spaced between 0.0001 and 0.02
betas = torch.linspace(0.0001, 0.02, num_diffusion_steps)

# Since our targets are scalars, dim = 1
dim = 1
embedding_dim = 32  # As used in get_time_embedding
# Instantiate the denoising network
denoise_net = model_architecture(dim, embedding_dim, hidden_size=256)
# Define the optimizer
optimizer = torch.optim.Adam(denoise_net.parameters(), lr=learning_rate)

for epoch in range(num_epochs):
    for x0 in train_loader:  # x0 has shape [batch_size] or [batch_size, 1]
        # If necessary, reshape x0 to [batch_size, dim] (here dim might be 1)
        # x0 = x0.unsqueeze(1)  if it's a scalar
        # print(x0.shape)
        
        # Sample a random diffusion timestep for each sample in the batch
        t = torch.randint(0, num_diffusion_steps, (batch_size,), dtype=torch.long)
        # print(t.shape)
        
        # Generate the noisy sample and the true noise using forward diffusion
        x_t, true_noise = forward_diffusion_sample(x0, t, betas)
        
        # Use the reverse diffusion function to predict the noise
        predicted_noise = reverse_diffusion_sample(x_t, betas, t, embedding_dim, denoise_net)
        
        # Compute the loss (MSE between predicted noise and true noise)
        loss = F.mse_loss(predicted_noise, true_noise)
        
        # Backpropagate and update the network parameters
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    
    print(f"Epoch {epoch+1}, Loss: {loss.item()}")

Epoch 1, Loss: 0.47396522760391235
Epoch 2, Loss: 0.5742954015731812
Epoch 3, Loss: 0.5933837890625
Epoch 4, Loss: 0.7202255725860596
Epoch 5, Loss: 0.34455788135528564
Epoch 6, Loss: 0.21193692088127136
Epoch 7, Loss: 0.23508334159851074
Epoch 8, Loss: 0.49866870045661926
Epoch 9, Loss: 0.1860816478729248
Epoch 10, Loss: 0.4293581247329712
Epoch 11, Loss: 0.5209160447120667
Epoch 12, Loss: 0.3300785422325134
Epoch 13, Loss: 0.2333860993385315
Epoch 14, Loss: 0.5953035950660706
Epoch 15, Loss: 0.22856773436069489
Epoch 16, Loss: 0.24293376505374908
Epoch 17, Loss: 0.24218028783798218
Epoch 18, Loss: 0.27146539092063904
Epoch 19, Loss: 0.31763091683387756
Epoch 20, Loss: 0.4374973177909851
Epoch 21, Loss: 0.31849151849746704
Epoch 22, Loss: 0.42059147357940674
Epoch 23, Loss: 0.28873878717422485
Epoch 24, Loss: 0.2215581089258194
Epoch 25, Loss: 0.761014461517334
Epoch 26, Loss: 0.22949521243572235
Epoch 27, Loss: 0.4238676130771637
Epoch 28, Loss: 0.505625307559967
Epoch 29, Loss: 0.31